### ISSUE TITLE
Anwers

### ISSUE THREAD

**Issue by dronov** [rishiip/ruby-on-rails-interview-questions#1]
Hello!

What do you think about adding answers for questions? I think it would be interesting for some people.

**Comment by rishiip** [comment]
@dronov : Actually I was thinking about the same! If you are interested to write answer to any question, you may send pull request for the same.

We would discuss the answer, modify it if it needs change and merge it.

**Comment by dronov** [comment]
@rishiip good idea. Thank you!
I will try to make some PR's using this issue :+1:

**Comment by rishiip** [comment]
@dronov What do your thinking regarding adding answers to these question.

Do we have to provide only links for each answer or write whole answer within the same file?

**Comment by dronov** [comment]
@rishiip we could start from describing links like #3 
If the main file will be grow up we can make a new file structure for answers.

**Comment by rishiip** [comment]
@dronov Sure! Looks good :+1: 

A Little change, can we make it like following for improving readability?

##### What's the major improvements in Rails 5.0?
- A good article from [Site Point](http://www.sitepoint.com/whats-new-rails-5)
- Another good blog post from [Michelada](http://blog.michelada.io/whats-new-in-rails-5)

**Comment by dronov** [comment]
Sure. I've updated #3

**Comment by AjayBarot** [comment]
@rishiip : Please refer this.
: https://github.com/subbiah/ruby-interview-questions

**Comment by rishiip** [comment]
thanks :+1:
