### ISSUE TITLE
What is new in Rails version?

### ISSUE THREAD

**Issue by dronov** [rishiip/ruby-on-rails-interview-questions#2]
Hey @rishiip , [this question](https://github.com/rishiip/ruby-on-rails-interview-questions#what-is-new-in-rails--version) sounds unclear. What do you mean in particular?

**Comment by rishiip** [comment]
@dronov : The question is about describing new features available within latest version of Rails. i.e. 4.2, 5.0

**Comment by dronov** [comment]
@rishiip so I think it would be good to clarify the question like: What's the major improvements in Rails 5.0? I'm not sure that it will be interesting to talk about **all** of new features.
And the answer could be [here](http://www.sitepoint.com/whats-new-rails-5/).

**Comment by rishiip** [comment]
@dronov I have changed the question as per your suggestion, you may take a glance at the changes at b99de19aa374bf913701033b192694d16bbe0049 

Sometimes Interviewer ask about describing new features/improvements in latest version of Rails.

**Comment by dronov** [comment]
@rishiip sounds good! I would like to start adding an answers :) Let's go?
